-- File: obiettivi_schema.sql
-- Descrizione: Schema per la gestione degli obiettivi

-- Tabella dei periodi degli obiettivi
CREATE TABLE PERIODI_OBIETTIVI (
    ID_PERIODO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ANNO INTEGER NOT NULL,
    NOME_PERIODO VARCHAR(50) NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE NOT NULL,
    STATO VARCHAR(15) NOT NULL, -- 'PIANIFICAZIONE', 'ATTIVO', 'CHIUSO'
    PRIMARY KEY (ID_PERIODO),
    UNIQUE (ANNO, NOME_PERIODO)
);

-- Tabella dei tipi di obiettivi
CREATE TABLE TIPI_OBIETTIVI (
    ID_TIPO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME_TIPO VARCHAR(50) NOT NULL,
    DESCRIZIONE VARCHAR(200),
    ATTIVO CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_TIPO),
    UNIQUE (NOME_TIPO)
);

-- Tabella degli obiettivi dipartimentali
CREATE TABLE OBIETTIVI_DIPARTIMENTO (
    ID_OBIETTIVO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPARTIMENTO INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    ID_TIPO INTEGER NOT NULL,
    TITOLO VARCHAR(100) NOT NULL,
    DESCRIZIONE VARCHAR(500),
    CRITERIO_SUCCESSO VARCHAR(200) NOT NULL,
    PESO DECIMAL(3,2) NOT NULL, -- Valore tra 0 e 1
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    DATA_APPROVAZIONE TIMESTAMP,
    ID_APPROVATORE INTEGER,
    STATO VARCHAR(15) NOT NULL, -- 'BOZZA', 'APPROVATO', 'ASSEGNATO', 'COMPLETATO'
    PRIMARY KEY (ID_OBIETTIVO),
    FOREIGN KEY (ID_DIPARTIMENTO) REFERENCES DIPARTIMENTI(ID_DIPARTIMENTO),
    FOREIGN KEY (ID_PERIODO) REFERENCES PERIODI_OBIETTIVI(ID_PERIODO),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPI_OBIETTIVI(ID_TIPO),
    FOREIGN KEY (ID_APPROVATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella degli obiettivi individuali
CREATE TABLE OBIETTIVI_INDIVIDUALI (
    ID_OBIETTIVO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    ID_TIPO INTEGER NOT NULL,
    ID_OBIETTIVO_DIPARTIMENTO INTEGER, -- Obiettivo dipartimentale collegato (opzionale)
    TITOLO VARCHAR(100) NOT NULL,
    DESCRIZIONE VARCHAR(500),
    CRITERIO_SUCCESSO VARCHAR(200) NOT NULL,
    PESO DECIMAL(3,2) NOT NULL, -- Valore tra 0 e 1
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    DATA_APPROVAZIONE TIMESTAMP,
    ID_APPROVATORE INTEGER,
    STATO VARCHAR(15) NOT NULL, -- 'BOZZA', 'APPROVATO', 'IN_CORSO', 'VALUTATO', 'COMPLETATO'
    PUNTEGGIO DECIMAL(4,2), -- Punteggio finale dell'obiettivo
    COMMENTI_MANAGER VARCHAR(500),
    COMMENTI_DIPENDENTE VARCHAR(500),
    PRIMARY KEY (ID_OBIETTIVO),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE),
    FOREIGN KEY (ID_PERIODO) REFERENCES PERIODI_OBIETTIVI(ID_PERIODO),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPI_OBIETTIVI(ID_TIPO),
    FOREIGN KEY (ID_OBIETTIVO_DIPARTIMENTO) REFERENCES OBIETTIVI_DIPARTIMENTO(ID_OBIETTIVO),
    FOREIGN KEY (ID_APPROVATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella dei check-in di progresso
CREATE TABLE CHECKIN_OBIETTIVI (
    ID_CHECKIN INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_OBIETTIVO INTEGER NOT NULL,
    DATA_CHECKIN DATE NOT NULL,
    STATO_AVANZAMENTO VARCHAR(20) NOT NULL, -- 'NON_INIZIATO', 'IN_CORSO', 'A_RISCHIO', 'COMPLETATO'
    PERCENTUALE_COMPLETAMENTO INTEGER,
    COMMENTI VARCHAR(500),
    ID_CREATORE INTEGER NOT NULL,
    PRIMARY KEY (ID_CHECKIN),
    FOREIGN KEY (ID_OBIETTIVO) REFERENCES OBIETTIVI_INDIVIDUALI(ID_OBIETTIVO),
    FOREIGN KEY (ID_CREATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Indici per le performance
CREATE INDEX IDX_OBIETTIVI_DIPARTIMENTO ON OBIETTIVI_DIPARTIMENTO(ID_DIPARTIMENTO);
CREATE INDEX IDX_OBIETTIVI_DIPARTIMENTO_PERIODO ON OBIETTIVI_DIPARTIMENTO(ID_PERIODO);
CREATE INDEX IDX_OBIETTIVI_INDIVIDUALI_DIPENDENTE ON OBIETTIVI_INDIVIDUALI(ID_DIPENDENTE);
CREATE INDEX IDX_OBIETTIVI_INDIVIDUALI_PERIODO ON OBIETTIVI_INDIVIDUALI(ID_PERIODO);
CREATE INDEX IDX_OBIETTIVI_INDIVIDUALI_STATO ON OBIETTIVI_INDIVIDUALI(STATO);
CREATE INDEX IDX_CHECKIN_OBIETTIVO ON CHECKIN_OBIETTIVI(ID_OBIETTIVO);