-- File: report_performance.sql
-- Descrizione: Query per report delle performance

-- Query per report valutazioni per dipendente
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    CV.ANNO,
    CV.NOME_CICLO,
    V.PUNTEGGIO_TOTALE,
    V.DATA_VALUTAZIONE,
    DVAL.NOME AS NOME_VALUTATORE
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
JOIN VALUTAZIONI V ON D.ID_DIPENDENTE = V.ID_DIPENDENTE
JOIN CICLI_VALUTAZIONE CV ON V.ID_CICLO = CV.ID_CICLO
JOIN DIPENDENTI DVAL ON V.ID_VALUTATORE = DVAL.ID_DIPENDENTE
WHERE CV.ANNO = :HV-ANNO
AND V.STATO = 'COMPLETATA'
ORDER BY DP.NOME_DIPARTIMENTO, D.NOME;

-- Query per report punteggi per categoria
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    CV.ANNO,
    CV.NOME_CICLO,
    CAT.NOME_CATEGORIA,
    DV.PUNTEGGIO,
    DV.PESO,
    DV.PUNTEGGIO * DV.PESO AS PUNTEGGIO_PESATO
FROM DIPENDENTI D
JOIN VALUTAZIONI V ON D.ID_DIPENDENTE = V.ID_DIPENDENTE
JOIN CICLI_VALUTAZIONE CV ON V.ID_CICLO = CV.ID_CICLO
JOIN DETTAGLI_VALUTAZIONE DV ON V.ID_VALUTAZIONE = DV.ID_VALUTAZIONE
JOIN CATEGORIE_VALUTAZIONE CAT ON DV.ID_CATEGORIA = CAT.ID_CATEGORIA
WHERE CV.ANNO = :HV-ANNO
AND D.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND V.STATO = 'COMPLETATA'
ORDER BY CAT.NOME_CATEGORIA;

-- Query per report media punteggi per dipartimento
SELECT 
    DP.NOME_DIPARTIMENTO,
    COUNT(DISTINCT V.ID_DIPENDENTE) AS NUMERO_DIPENDENTI,
    AVG(V.PUNTEGGIO_TOTALE) AS MEDIA_PUNTEGGIO,
    MIN(V.PUNTEGGIO_TOTALE) AS PUNTEGGIO_MINIMO,
    MAX(V.PUNTEGGIO_TOTALE) AS PUNTEGGIO_MASSIMO
FROM DIPARTIMENTI DP
JOIN POSIZIONI P ON DP.ID_DIPARTIMENTO = P.ID_DIPARTIMENTO
JOIN DIPENDENTI D ON P.ID_POSIZIONE = D.ID_POSIZIONE
JOIN VALUTAZIONI V ON D.ID_DIPENDENTE = V.ID_DIPENDENTE
JOIN CICLI_VALUTAZIONE CV ON V.ID_CICLO = CV.ID_CICLO
WHERE CV.ANNO = :HV-ANNO
AND CV.NOME_CICLO = :HV-NOME-CICLO
AND V.STATO = 'COMPLETATA'
GROUP BY DP.NOME_DIPARTIMENTO
ORDER BY MEDIA_PUNTEGGIO DESC;

-- Query per report trend valutazioni per dipendente
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    CV.ANNO,
    CV.NOME_CICLO,
    V.PUNTEGGIO_TOTALE
FROM DIPENDENTI D
JOIN VALUTAZIONI V ON D.ID_DIPENDENTE = V.ID_DIPENDENTE
JOIN CICLI_VALUTAZIONE CV ON V.ID_CICLO = CV.ID_CICLO
WHERE D.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND V.STATO = 'COMPLETATA'
ORDER BY CV.ANNO, CV.NOME_CICLO;

-- Query per report media punteggi per categoria
SELECT 
    CAT.NOME_CATEGORIA,
    AVG(DV.PUNTEGGIO) AS MEDIA_PUNTEGGIO,
    MIN(DV.PUNTEGGIO) AS PUNTEGGIO_MINIMO,
    MAX(DV.PUNTEGGIO) AS PUNTEGGIO_MASSIMO,
    COUNT(DISTINCT V.ID_DIPENDENTE) AS NUMERO_DIPENDENTI
FROM CATEGORIE_VALUTAZIONE CAT
JOIN DETTAGLI_VALUTAZIONE DV ON CAT.ID_CATEGORIA = DV.ID_CATEGORIA
JOIN VALUTAZIONI V ON DV.ID_VALUTAZIONE = V.ID_VALUTAZIONE
JOIN CICLI_VALUTAZIONE CV ON V.ID_CICLO = CV.ID_CICLO
WHERE CV.ANNO = :HV-ANNO
AND CV.NOME_CICLO = :HV-NOME-CICLO
AND V.STATO = 'COMPLETATA'
GROUP BY CAT.NOME_CATEGORIA
ORDER BY MEDIA_PUNTEGGIO DESC;

-- Query per report top/bottom performer
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    V.PUNTEGGIO_TOTALE
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
JOIN VALUTAZIONI V ON D.ID_DIPENDENTE = V.ID_DIPENDENTE
JOIN CICLI_VALUTAZIONE CV ON V.ID_CICLO = CV.ID_CICLO
WHERE CV.ANNO = :HV-ANNO
AND CV.NOME_CICLO = :HV-NOME-CICLO
AND V.STATO = 'COMPLETATA'
ORDER BY V.PUNTEGGIO_TOTALE DESC
FETCH FIRST 10 ROWS ONLY;