-- File: valutazioni_schema.sql
-- Descrizione: Schema per la gestione delle valutazioni dei dipendenti

-- Tabella dei cicli di valutazione
CREATE TABLE CICLI_VALUTAZIONE (
    ID_CICLO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ANNO INTEGER NOT NULL,
    NOME_CICLO VARCHAR(50) NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE NOT NULL,
    STATO VARCHAR(15) NOT NULL, -- 'PIANIFICATO', 'IN_CORSO', 'COMPLETATO'
    DESCRIZIONE VARCHAR(200),
    PRIMARY KEY (ID_CICLO),
    UNIQUE (ANNO, NOME_CICLO)
);

-- Tabella delle categorie di valutazione
CREATE TABLE CATEGORIE_VALUTAZIONE (
    ID_CATEGORIA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME_CATEGORIA VARCHAR(50) NOT NULL,
    DESCRIZIONE VARCHAR(200),
    PESO_DEFAULT DECIMAL(3,2) NOT NULL, -- Valore tra 0 e 1
    ATTIVA CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_CATEGORIA),
    UNIQUE (NOME_CATEGORIA)
);

-- Tabella delle valutazioni
CREATE TABLE VALUTAZIONI (
    ID_VALUTAZIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    ID_CICLO INTEGER NOT NULL,
    ID_VALUTATORE INTEGER NOT NULL, -- ID del manager che fa la valutazione
    DATA_VALUTAZIONE DATE NOT NULL,
    STATO VARCHAR(15) NOT NULL, -- 'BOZZA', 'COMPLETATA', 'CONDIVISA'
    PUNTEGGIO_TOTALE DECIMAL(4,2),
    COMMENTI_VALUTATORE VARCHAR(1000),
    COMMENTI_DIPENDENTE VARCHAR(1000),
    DATA_COLLOQUIO DATE,
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    DATA_MODIFICA TIMESTAMP,
    PRIMARY KEY (ID_VALUTAZIONE),
    UNIQUE (ID_DIPENDENTE, ID_CICLO),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE),
    FOREIGN KEY (ID_CICLO) REFERENCES CICLI_VALUTAZIONE(ID_CICLO),
    FOREIGN KEY (ID_VALUTATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella dei dettagli valutazione per categoria
CREATE TABLE DETTAGLI_VALUTAZIONE (
    ID_DETTAGLIO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_VALUTAZIONE INTEGER NOT NULL,
    ID_CATEGORIA INTEGER NOT NULL,
    PUNTEGGIO DECIMAL(4,2) NOT NULL, -- Es. valori da 1 a 5
    PESO DECIMAL(3,2) NOT NULL, -- Valore tra 0 e 1
    COMMENTI VARCHAR(500),
    PRIMARY KEY (ID_DETTAGLIO),
    UNIQUE (ID_VALUTAZIONE, ID_CATEGORIA),
    FOREIGN KEY (ID_VALUTAZIONE) REFERENCES VALUTAZIONI(ID_VALUTAZIONE),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIE_VALUTAZIONE(ID_CATEGORIA)
);

-- Indici per le performance
CREATE INDEX IDX_VALUTAZIONI_DIPENDENTE ON VALUTAZIONI(ID_DIPENDENTE);
CREATE INDEX IDX_VALUTAZIONI_CICLO ON VALUTAZIONI(ID_CICLO);
CREATE INDEX IDX_VALUTAZIONI_VALUTATORE ON VALUTAZIONI(ID_VALUTATORE);
CREATE INDEX IDX_DETTAGLI_VALUTAZIONE ON DETTAGLI_VALUTAZIONE(ID_VALUTAZIONE);