-- File: bonus_gestione.sql
-- Descrizione: Query per la gestione dei bonus

-- Query per inserire un nuovo bonus
INSERT INTO BONUS (
    ID_DIPENDENTE, ID_PERIODO, TIPO_BONUS, IMPORTO, 
    DESCRIZIONE, DATA_INSERIMENTO, ID_UTENTE_INSERIMENTO
) VALUES (
    :HV-ID-DIPENDENTE, :HV-ID-PERIODO, :HV-TIPO-BONUS, :HV-IMPORTO,
    :HV-DESCRIZIONE, CURRENT TIMESTAMP, :HV-ID-UTENTE-INSERIMENTO
);

-- Query per tutti i bonus di un dipendente in un periodo
SELECT 
    B.ID_BONUS,
    B.TIPO_BONUS,
    B.IMPORTO,
    B.DESCRIZIONE,
    B.DATA_INSERIMENTO,
    D.NOME AS NOME_UTENTE_INSERIMENTO
FROM BONUS B
LEFT JOIN DIPENDENTI D ON B.ID_UTENTE_INSERIMENTO = D.ID_DIPENDENTE
WHERE B.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND B.ID_PERIODO = :HV-ID-PERIODO
ORDER BY B.DATA_INSERIMENTO DESC;

-- Query per aggiornare un bonus esistente
UPDATE BONUS
SET TIPO_BONUS = :HV-TIPO-BONUS,
    IMPORTO = :HV-IMPORTO,
    DESCRIZIONE = :HV-DESCRIZIONE,
    DATA_INSERIMENTO = CURRENT TIMESTAMP,
    ID_UTENTE_INSERIMENTO = :HV-ID-UTENTE-INSERIMENTO
WHERE ID_BONUS = :HV-ID-BONUS;

-- Query per eliminare un bonus
DELETE FROM BONUS
WHERE ID_BONUS = :HV-ID-BONUS;

-- Query per calcolare il totale dei bonus per un dipendente in un periodo
SELECT 
    SUM(IMPORTO) AS TOTALE_BONUS
FROM BONUS
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND ID_PERIODO = :HV-ID-PERIODO;

-- Query per riepilogo bonus per tipo
SELECT 
    TIPO_BONUS,
    COUNT(*) AS NUMERO_BONUS,
    SUM(IMPORTO) AS IMPORTO_TOTALE,
    AVG(IMPORTO) AS IMPORTO_MEDIO
FROM BONUS
WHERE ID_PERIODO = :HV-ID-PERIODO
GROUP BY TIPO_BONUS
ORDER BY IMPORTO_TOTALE DESC;

-- Query per riepilogo bonus per dipartimento
SELECT 
    DP.NOME_DIPARTIMENTO,
    COUNT(B.ID_BONUS) AS NUMERO_BONUS,
    SUM(B.IMPORTO) AS IMPORTO_TOTALE,
    AVG(B.IMPORTO) AS IMPORTO_MEDIO,
    COUNT(DISTINCT B.ID_DIPENDENTE) AS NUMERO_DIPENDENTI
FROM BONUS B
JOIN DIPENDENTI D ON B.ID_DIPENDENTE = D.ID_DIPENDENTE
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
WHERE B.ID_PERIODO = :HV-ID-PERIODO
GROUP BY DP.NOME_DIPARTIMENTO
ORDER BY IMPORTO_TOTALE DESC;

-- Query per bonus dei dipendenti con importo più alto
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    SUM(B.IMPORTO) AS TOTALE_BONUS
FROM BONUS B
JOIN DIPENDENTI D ON B.ID_DIPENDENTE = D.ID_DIPENDENTE
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
WHERE B.ID_PERIODO = :HV-ID-PERIODO
GROUP BY D.ID_DIPENDENTE, D.NOME, P.NOME_POSIZIONE, DP.NOME_DIPARTIMENTO
ORDER BY TOTALE_BONUS DESC
FETCH FIRST 10 ROWS ONLY;

-- Query per storico bonus di un dipendente
SELECT 
    PP.ANNO,
    PP.MESE,
    B.TIPO_BONUS,
    B.IMPORTO,
    B.DESCRIZIONE,
    B.DATA_INSERIMENTO
FROM BONUS B
JOIN PERIODI_PAGA PP ON B.ID_PERIODO = PP.ID_PERIODO
WHERE B.ID_DIPENDENTE = :HV-ID-DIPENDENTE
ORDER BY PP.ANNO DESC, PP.MESE DESC, B.DATA_INSERIMENTO DESC;