-- File: query_stipendi.sql
-- Descrizione: Query complesse per la gestione degli stipendi

-- Query per calcolo stipendio di un dipendente in un periodo
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    PP.ANNO,
    PP.MESE,
    P.STIPENDIO_BASE,
    COALESCE(S.ORE_LAVORATE, 0) AS ORE_LAVORATE,
    COALESCE(S.GIORNI_LAVORATI, 0) AS GIORNI_LAVORATI,
    COALESCE(S.BONUS, 0) AS TOTALE_BONUS,
    COALESCE(S.TRATTENUTE, 0) AS TOTALE_TRATTENUTE,
    COALESCE(S.STIPENDIO_NETTO, P.STIPENDIO_BASE) AS STIPENDIO_NETTO
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN PERIODI_PAGA PP ON PP.ANNO = :HV-ANNO AND PP.MESE = :HV-MESE
LEFT JOIN STIPENDI S ON D.ID_DIPENDENTE = S.ID_DIPENDENTE AND PP.ID_PERIODO = S.ID_PERIODO
WHERE D.ID_DIPENDENTE = :HV-ID-DIPENDENTE;

-- Query per riepilogo stipendi per periodo
SELECT 
    PP.ANNO,
    PP.MESE,
    COUNT(S.ID_STIPENDIO) AS STIPENDI_ELABORATI,
    SUM(S.STIPENDIO_BASE) AS TOTALE_STIPENDI_BASE,
    SUM(S.BONUS) AS TOTALE_BONUS,
    SUM(S.TRATTENUTE) AS TOTALE_TRATTENUTE,
    SUM(S.STIPENDIO_NETTO) AS TOTALE_STIPENDI_NETTI
FROM PERIODI_PAGA PP
LEFT JOIN STIPENDI S ON PP.ID_PERIODO = S.ID_PERIODO
WHERE PP.ANNO = :HV-ANNO
GROUP BY PP.ANNO, PP.MESE
ORDER BY PP.ANNO, PP.MESE;

-- Query per riepilogo stipendi per dipartimento
SELECT 
    DP.NOME_DIPARTIMENTO,
    COUNT(S.ID_STIPENDIO) AS NUMERO_STIPENDI,
    SUM(S.STIPENDIO_BASE) AS TOTALE_STIPENDI_BASE,
    SUM(S.BONUS) AS TOTALE_BONUS,
    SUM(S.TRATTENUTE) AS TOTALE_TRATTENUTE,
    SUM(S.STIPENDIO_NETTO) AS TOTALE_STIPENDI_NETTI,
    AVG(S.STIPENDIO_NETTO) AS STIPENDIO_MEDIO
FROM DIPARTIMENTI DP
JOIN POSIZIONI P ON DP.ID_DIPARTIMENTO = P.ID_DIPARTIMENTO
JOIN DIPENDENTI D ON P.ID_POSIZIONE = D.ID_POSIZIONE
JOIN STIPENDI S ON D.ID_DIPENDENTE = S.ID_DIPENDENTE
JOIN PERIODI_PAGA PP ON S.ID_PERIODO = PP.ID_PERIODO
WHERE PP.ANNO = :HV-ANNO AND PP.MESE = :HV-MESE
GROUP BY DP.NOME_DIPARTIMENTO
ORDER BY TOTALE_STIPENDI_NETTI DESC;

-- Query per dettaglio bonus per dipendente e periodo
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    PP.ANNO,
    PP.MESE,
    B.TIPO_BONUS,
    B.IMPORTO,
    B.DESCRIZIONE,
    B.DATA_INSERIMENTO
FROM DIPENDENTI D
JOIN BONUS B ON D.ID_DIPENDENTE = B.ID_DIPENDENTE
JOIN PERIODI_PAGA PP ON B.ID_PERIODO = PP.ID_PERIODO
WHERE D.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND PP.ANNO = :HV-ANNO AND PP.MESE = :HV-MESE
ORDER BY B.DATA_INSERIMENTO;

-- Query per dettaglio trattenute per dipendente e periodo
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    PP.ANNO,
    PP.MESE,
    T.TIPO_TRATTENUTA,
    T.IMPORTO,
    T.DESCRIZIONE,
    T.DATA_INSERIMENTO
FROM DIPENDENTI D
JOIN TRATTENUTE T ON D.ID_DIPENDENTE = T.ID_DIPENDENTE
JOIN PERIODI_PAGA PP ON T.ID_PERIODO = PP.ID_PERIODO
WHERE D.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND PP.ANNO = :HV-ANNO AND PP.MESE = :HV-MESE
ORDER BY T.DATA_INSERIMENTO;

-- Query per storico stipendi di un dipendente
SELECT 
    PP.ANNO,
    PP.MESE,
    S.STIPENDIO_BASE,
    S.BONUS,
    S.TRATTENUTE,
    S.STIPENDIO_NETTO,
    P.NOME_POSIZIONE
FROM STIPENDI S
JOIN PERIODI_PAGA PP ON S.ID_PERIODO = PP.ID_PERIODO
JOIN DIPENDENTI D ON S.ID_DIPENDENTE = D.ID_DIPENDENTE
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
WHERE D.ID_DIPENDENTE = :HV-ID-DIPENDENTE
ORDER BY PP.ANNO DESC, PP.MESE DESC;