-- File: stipendi_calcolo.sql
-- Descrizione: Query per il calcolo degli stipendi

-- Query per ottenere lo stipendio base del dipendente dalla posizione
SELECT D.ID_DIPENDENTE, D.NOME, P.STIPENDIO_BASE, P.NOME_POSIZIONE
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
WHERE D.ID_DIPENDENTE = :HV-ID-DIPENDENTE;

-- Query per ottenere tutti i bonus di un dipendente per un periodo
SELECT ID_BONUS, TIPO_BONUS, IMPORTO, DESCRIZIONE
FROM BONUS
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND ID_PERIODO = :HV-ID-PERIODO;

-- Query per ottenere tutte le trattenute di un dipendente per un periodo
SELECT ID_TRATTENUTA, TIPO_TRATTENUTA, IMPORTO, DESCRIZIONE
FROM TRATTENUTE
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND ID_PERIODO = :HV-ID-PERIODO;

-- Query per calcolare la somma dei bonus per un dipendente in un periodo
SELECT SUM(IMPORTO) AS TOTALE_BONUS
FROM BONUS
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND ID_PERIODO = :HV-ID-PERIODO;

-- Query per calcolare la somma delle trattenute per un dipendente in un periodo
SELECT SUM(IMPORTO) AS TOTALE_TRATTENUTE
FROM TRATTENUTE
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND ID_PERIODO = :HV-ID-PERIODO;

-- Query per inserire un nuovo stipendio elaborato
INSERT INTO STIPENDI (
    ID_DIPENDENTE, ID_PERIODO, STIPENDIO_BASE, 
    ORE_LAVORATE, GIORNI_LAVORATI, 
    BONUS, TRATTENUTE, STIPENDIO_NETTO, DATA_ELABORAZIONE
) VALUES (
    :HV-ID-DIPENDENTE, :HV-ID-PERIODO, :HV-STIPENDIO-BASE,
    :HV-ORE-LAVORATE, :HV-GIORNI-LAVORATI,
    :HV-BONUS, :HV-TRATTENUTE, :HV-STIPENDIO-NETTO, CURRENT TIMESTAMP
);

-- Query per aggiornare uno stipendio esistente
UPDATE STIPENDI
SET STIPENDIO_BASE = :HV-STIPENDIO-BASE,
    ORE_LAVORATE = :HV-ORE-LAVORATE,
    GIORNI_LAVORATI = :HV-GIORNI-LAVORATI,
    BONUS = :HV-BONUS,
    TRATTENUTE = :HV-TRATTENUTE,
    STIPENDIO_NETTO = :HV-STIPENDIO-NETTO,
    DATA_ELABORAZIONE = CURRENT TIMESTAMP
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND ID_PERIODO = :HV-ID-PERIODO;