-- File: stipendi_schema.sql
-- Descrizione: Schema per la gestione degli stipendi e bonus

-- Tabella dei periodi di paga
CREATE TABLE PERIODI_PAGA (
    ID_PERIODO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ANNO INTEGER NOT NULL,
    MESE INTEGER NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE NOT NULL,
    STATO VARCHAR(10) NOT NULL, -- 'APERTO', 'CHIUSO', 'ELABORATO'
    DATA_ELABORAZIONE DATE,
    PRIMARY KEY (ID_PERIODO),
    UNIQUE (ANNO, MESE)
);

-- Tabella degli stipendi
CREATE TABLE STIPENDI (
    ID_STIPENDIO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    STIPENDIO_BASE DECIMAL(8,2) NOT NULL,
    ORE_LAVORATE DECIMAL(5,2),
    GIORNI_LAVORATI INTEGER,
    BONUS DECIMAL(8,2) DEFAULT 0,
    TRATTENUTE DECIMAL(8,2) DEFAULT 0,
    STIPENDIO_NETTO DECIMAL(8,2) NOT NULL,
    DATA_ELABORAZIONE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_STIPENDIO),
    UNIQUE (ID_DIPENDENTE, ID_PERIODO),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE),
    FOREIGN KEY (ID_PERIODO) REFERENCES PERIODI_PAGA(ID_PERIODO)
);

-- Tabella dei bonus
CREATE TABLE BONUS (
    ID_BONUS INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    TIPO_BONUS VARCHAR(30) NOT NULL, -- 'PRODUTTIVITA', 'STRAORDINARIO', 'UNA_TANTUM'
    IMPORTO DECIMAL(8,2) NOT NULL,
    DESCRIZIONE VARCHAR(100),
    DATA_INSERIMENTO TIMESTAMP NOT NULL,
    ID_UTENTE_INSERIMENTO INTEGER,
    PRIMARY KEY (ID_BONUS),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE),
    FOREIGN KEY (ID_PERIODO) REFERENCES PERIODI_PAGA(ID_PERIODO)
);

-- Tabella delle trattenute
CREATE TABLE TRATTENUTE (
    ID_TRATTENUTA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    TIPO_TRATTENUTA VARCHAR(30) NOT NULL, -- 'FISCALE', 'PREVIDENZIALE', 'ALTRO'
    IMPORTO DECIMAL(8,2) NOT NULL,
    DESCRIZIONE VARCHAR(100),
    DATA_INSERIMENTO TIMESTAMP NOT NULL,
    ID_UTENTE_INSERIMENTO INTEGER,
    PRIMARY KEY (ID_TRATTENUTA),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE),
    FOREIGN KEY (ID_PERIODO) REFERENCES PERIODI_PAGA(ID_PERIODO)
);

-- Indici per le performance
CREATE INDEX IDX_STIPENDI_PERIODO ON STIPENDI(ID_PERIODO);
CREATE INDEX IDX_STIPENDI_DIPENDENTE ON STIPENDI(ID_DIPENDENTE);
CREATE INDEX IDX_BONUS_PERIODO ON BONUS(ID_PERIODO);
CREATE INDEX IDX_BONUS_DIPENDENTE ON BONUS(ID_DIPENDENTE);
CREATE INDEX IDX_TRATTENUTE_PERIODO ON TRATTENUTE(ID_PERIODO);
CREATE INDEX IDX_TRATTENUTE_DIPENDENTE ON TRATTENUTE(ID_DIPENDENTE);