version: '3.8'

services:
  cobol-app:
    image: cobol-db2:local
    container_name: cobol-app
    volumes:
      - .:/app
    depends_on:
      - db2
    networks:
      - cobol-network
    tty: true
    stdin_open: true

  db2:
    image: ibmcom/db2
    container_name: mydb2
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
      - DBNAME=DIPDB
      - PERSISTENT_HOME=false
      - ARCHIVE_LOGS=false
    ports:
      - "50000:50000"
    volumes:
      - db2-data:/database
      - ./db:/tmp/db
    networks:
      - cobol-network

networks:
  cobol-network:
    driver: bridge

volumes:
  db2-data: