-- File: approvazioni_workflow.sql
-- Descrizione: Schema per il workflow di approvazione

-- Tabella delle autorizzazioni per dipartimento
CREATE TABLE AUTORIZZAZIONI_DIPARTIMENTO (
    ID_AUTORIZZAZIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPARTIMENTO INTEGER NOT NULL,
    ID_APPROVATORE INTEGER NOT NULL, -- ID dipendente autorizzato ad approvare
    LIMITE_IMPORTO DECIMAL(12,2) NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE,
    ATTIVA CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_AUTORIZZAZIONE),
    FOREIGN KEY (ID_DIPARTIMENTO) REFERENCES DIPARTIMENTI(ID_DIPARTIMENTO),
    FOREIGN KEY (ID_APPROVATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella dei livelli di approvazione
CREATE TABLE LIVELLI_APPROVAZIONE (
    ID_LIVELLO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME_LIVELLO VARCHAR(50) NOT NULL,
    SOGLIA_MIN DECIMAL(12,2),
    SOGLIA_MAX DECIMAL(12,2),
    ORDINE_APPROVAZIONE INTEGER NOT NULL,
    DESCRIZIONE VARCHAR(200),
    ATTIVO CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_LIVELLO),
    UNIQUE (NOME_LIVELLO)
);

-- Tabella delle approvazioni richieste
CREATE TABLE APPROVAZIONI_RICHIESTE (
    ID_APPROVAZIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_RICHIESTA INTEGER NOT NULL, -- ID della richiesta d'acquisto
    ID_LIVELLO INTEGER NOT NULL,
    ID_APPROVATORE INTEGER,
    STATO VARCHAR(15) NOT NULL, -- 'IN_ATTESA', 'APPROVATA', 'RIFIUTATA'
    DATA_RICHIESTA TIMESTAMP NOT NULL,
    DATA_APPROVAZIONE TIMESTAMP,
    COMMENTI VARCHAR(500),
    PRIMARY KEY (ID_APPROVAZIONE),
    UNIQUE (ID_RICHIESTA, ID_LIVELLO),
    FOREIGN KEY (ID_RICHIESTA) REFERENCES RICHIESTE_ACQUISTO(ID_RICHIESTA),
    FOREIGN KEY (ID_LIVELLO) REFERENCES LIVELLI_APPROVAZIONE(ID_LIVELLO),
    FOREIGN KEY (ID_APPROVATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella della deleghe di approvazione
CREATE TABLE DELEGHE_APPROVAZIONE (
    ID_DELEGA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DELEGANTE INTEGER NOT NULL, -- Dipendente che delega
    ID_DELEGATO INTEGER NOT NULL, -- Dipendente delegato
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE NOT NULL,
    MOTIVO VARCHAR(200),
    ATTIVA CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_DELEGA),
    FOREIGN KEY (ID_DELEGANTE) REFERENCES DIPENDENTI(ID_DIPENDENTE),
    FOREIGN KEY (ID_DELEGATO) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella dello storico approvazioni
CREATE TABLE STORICO_APPROVAZIONI (
    ID_STORICO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_APPROVAZIONE INTEGER NOT NULL,
    ID_APPROVATORE INTEGER NOT NULL,
    STATO_PRECEDENTE VARCHAR(15) NOT NULL,
    STATO_NUOVO VARCHAR(15) NOT NULL,
    DATA_MODIFICA TIMESTAMP NOT NULL,
    COMMENTI VARCHAR(500),
    PRIMARY KEY (ID_STORICO),
    FOREIGN KEY (ID_APPROVAZIONE) REFERENCES APPROVAZIONI_RICHIESTE(ID_APPROVAZIONE),
    FOREIGN KEY (ID_APPROVATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Indici per le performance
CREATE INDEX IDX_AUTORIZZAZIONI_DIPARTIMENTO ON AUTORIZZAZIONI_DIPARTIMENTO(ID_DIPARTIMENTO);
CREATE INDEX IDX_AUTORIZZAZIONI_APPROVATORE ON AUTORIZZAZIONI_DIPARTIMENTO(ID_APPROVATORE);
CREATE INDEX IDX_APPROVAZIONI_RICHIESTA ON APPROVAZIONI_RICHIESTE(ID_RICHIESTA);
CREATE INDEX IDX_APPROVAZIONI_STATO ON APPROVAZIONI_RICHIESTE(STATO);
CREATE INDEX IDX_DELEGHE_DELEGANTE ON DELEGHE_APPROVAZIONE(ID_DELEGANTE);
CREATE INDEX IDX_DELEGHE_DELEGATO ON DELEGHE_APPROVAZIONE(ID_DELEGATO);
CREATE INDEX IDX_DELEGHE_ATTIVA ON DELEGHE_APPROVAZIONE(ATTIVA);