-- File: articoli_schema.sql
-- Descrizione: Schema per la gestione del catalogo articoli

-- Tabella dei fornitori
CREATE TABLE FORNITORI (
    ID_FORNITORE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    RAGIONE_SOCIALE VARCHAR(100) NOT NULL,
    PARTITA_IVA VARCHAR(20) NOT NULL,
    INDIRIZZO VARCHAR(200),
    CITTA VARCHAR(50),
    CAP VARCHAR(10),
    PROVINCIA VARCHAR(2),
    NAZIONE VARCHAR(50),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(100),
    SITO_WEB VARCHAR(100),
    PERSONA_RIFERIMENTO VARCHAR(100),
    ATTIVO CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    DATA_INSERIMENTO TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_FORNITORE),
    UNIQUE (PARTITA_IVA)
);

-- Tabella delle categorie articoli
CREATE TABLE CATEGORIE_ARTICOLI (
    ID_CATEGORIA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME_CATEGORIA VARCHAR(50) NOT NULL,
    CATEGORIA_PADRE INTEGER,
    DESCRIZIONE VARCHAR(200),
    ATTIVA CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_CATEGORIA),
    UNIQUE (NOME_CATEGORIA),
    FOREIGN KEY (CATEGORIA_PADRE) REFERENCES CATEGORIE_ARTICOLI(ID_CATEGORIA)
);

-- Tabella del catalogo articoli
CREATE TABLE CATALOGO_ARTICOLI (
    ID_ARTICOLO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODICE_ARTICOLO VARCHAR(20) NOT NULL,
    NOME_ARTICOLO VARCHAR(100) NOT NULL,
    DESCRIZIONE VARCHAR(500),
    ID_CATEGORIA INTEGER NOT NULL,
    UNITA_MISURA VARCHAR(10) NOT NULL, -- 'PZ', 'KG', 'LT', ecc.
    PREZZO_LISTINO DECIMAL(10,2) NOT NULL,
    ALIQUOTA_IVA DECIMAL(4,2) NOT NULL,
    ATTIVO CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    DATA_INSERIMENTO TIMESTAMP NOT NULL,
    DATA_MODIFICA TIMESTAMP,
    PRIMARY KEY (ID_ARTICOLO),
    UNIQUE (CODICE_ARTICOLO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIE_ARTICOLI(ID_CATEGORIA)
);

-- Tabella degli articoli dei fornitori
CREATE TABLE ARTICOLI_FORNITORI (
    ID_ARTICOLO_FORNITORE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_ARTICOLO INTEGER NOT NULL,
    ID_FORNITORE INTEGER NOT NULL,
    CODICE_FORNITORE VARCHAR(20),
    PREZZO DECIMAL(10,2) NOT NULL,
    TEMPO_CONSEGNA INTEGER, -- Giorni
    QUANTITA_MINIMA DECIMAL(10,2),
    PRIORITA INTEGER NOT NULL DEFAULT 1, -- 1=fornitore principale
    ATTIVO CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    DATA_ULTIMO_ACQUISTO DATE,
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_ARTICOLO_FORNITORE),
    UNIQUE (ID_ARTICOLO, ID_FORNITORE),
    FOREIGN KEY (ID_ARTICOLO) REFERENCES CATALOGO_ARTICOLI(ID_ARTICOLO),
    FOREIGN KEY (ID_FORNITORE) REFERENCES FORNITORI(ID_FORNITORE)
);

-- Indici per le performance
CREATE INDEX IDX_ARTICOLI_CATEGORIA ON CATALOGO_ARTICOLI(ID_CATEGORIA);
CREATE INDEX IDX_ARTICOLI_ATTIVO ON CATALOGO_ARTICOLI(ATTIVO);
CREATE INDEX IDX_ARTICOLI_FORNITORI_ARTICOLO ON ARTICOLI_FORNITORI(ID_ARTICOLO);
CREATE INDEX IDX_ARTICOLI_FORNITORI_FORNITORE ON ARTICOLI_FORNITORI(ID_FORNITORE);