-- File: inventario_schema.sql
-- Descrizione: Schema per la gestione dell'inventario

-- Tabella delle locazioni magazzino
CREATE TABLE LOCAZIONI_MAGAZZINO (
    ID_LOCAZIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODICE_LOCAZIONE VARCHAR(20) NOT NULL,
    DESCRIZIONE VARCHAR(100),
    AREA VARCHAR(50),
    SCAFFALE VARCHAR(20),
    RIPIANO VARCHAR(20),
    POSIZIONE VARCHAR(20),
    ATTIVA CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_LOCAZIONE),
    UNIQUE (CODICE_LOCAZIONE)
);

-- Tabella dell'inventario
CREATE TABLE INVENTARIO (
    ID_INVENTARIO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_ARTICOLO INTEGER NOT NULL,
    ID_LOCAZIONE INTEGER NOT NULL,
    QUANTITA_DISPONIBILE DECIMAL(10,2) NOT NULL DEFAULT 0,
    QUANTITA_IMPEGNATA DECIMAL(10,2) NOT NULL DEFAULT 0,
    VALORE_UNITARIO DECIMAL(10,2) NOT NULL,
    DATA_ULTIMO_MOVIMENTO TIMESTAMP,
    LOTTO VARCHAR(50),
    DATA_SCADENZA DATE,
    PRIMARY KEY (ID_INVENTARIO),
    UNIQUE (ID_ARTICOLO, ID_LOCAZIONE, LOTTO),
    FOREIGN KEY (ID_ARTICOLO) REFERENCES CATALOGO_ARTICOLI(ID_ARTICOLO),
    FOREIGN KEY (ID_LOCAZIONE) REFERENCES LOCAZIONI_MAGAZZINO(ID_LOCAZIONE)
);

-- Tabella dei movimenti di inventario
CREATE TABLE MOVIMENTI_INVENTARIO (
    ID_MOVIMENTO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DATA_MOVIMENTO TIMESTAMP NOT NULL,
    ID_ARTICOLO INTEGER NOT NULL,
    ID_LOCAZIONE INTEGER NOT NULL,
    TIPO_MOVIMENTO VARCHAR(20) NOT NULL, -- 'CARICO', 'SCARICO', 'TRASFERIMENTO', 'RETTIFICA'
    QUANTITA DECIMAL(10,2) NOT NULL,
    VALORE_UNITARIO DECIMAL(10,2) NOT NULL,
    VALORE_TOTALE DECIMAL(12,2) NOT NULL,
    ID_DETTAGLIO_RICEZIONE INTEGER, -- Per movimenti di carico da ricezione
    ID_ORDINE_USCITA INTEGER, -- Per movimenti di scarico per ordini interni
    ID_OPERATORE INTEGER NOT NULL, -- ID dipendente che ha effettuato il movimento
    CAUSALE VARCHAR(100) NOT NULL,
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_MOVIMENTO),
    FOREIGN KEY (ID_ARTICOLO) REFERENCES CATALOGO_ARTICOLI(ID_ARTICOLO),
    FOREIGN KEY (ID_LOCAZIONE) REFERENCES LOCAZIONI_MAGAZZINO(ID_LOCAZIONE),
    FOREIGN KEY (ID_DETTAGLIO_RICEZIONE) REFERENCES DETTAGLI_RICEZIONE(ID_DETTAGLIO_RICEZIONE),
    FOREIGN KEY (ID_OPERATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella per inventario fisico
CREATE TABLE INVENTARIO_FISICO (
    ID_INVENTARIO_FISICO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE,
    STATO VARCHAR(15) NOT NULL, -- 'PIANIFICATO', 'IN_CORSO', 'COMPLETATO'
    DESCRIZIONE VARCHAR(100),
    ID_RESPONSABILE INTEGER NOT NULL, -- ID dipendente responsabile
    NOTE VARCHAR(500),
    PRIMARY KEY (ID_INVENTARIO_FISICO),
    FOREIGN KEY (ID_RESPONSABILE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella per i rilevamenti dell'inventario fisico
CREATE TABLE RILEVAMENTI_INVENTARIO (
    ID_RILEVAMENTO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_INVENTARIO_FISICO INTEGER NOT NULL,
    ID_ARTICOLO INTEGER NOT NULL,
    ID_LOCAZIONE INTEGER NOT NULL,
    QUANTITA_SISTEMA DECIMAL(10,2) NOT NULL,
    QUANTITA_RILEVATA DECIMAL(10,2) NOT NULL,
    DIFFERENZA DECIMAL(10,2) NOT NULL,
    VALORE_DIFFERENZA DECIMAL(10,2) NOT NULL,
    DATA_RILEVAMENTO TIMESTAMP NOT NULL,
    ID_RILEVATORE INTEGER NOT NULL, -- ID dipendente che ha fatto il rilevamento
    STATO VARCHAR(15) NOT NULL, -- 'RILEVATO', 'VERIFICATO', 'RETTIFICATO'
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_RILEVAMENTO),
    UNIQUE (ID_INVENTARIO_FISICO, ID_ARTICOLO, ID_LOCAZIONE),
    FOREIGN KEY (ID_INVENTARIO_FISICO) REFERENCES INVENTARIO_FISICO(ID_INVENTARIO_FISICO),
    FOREIGN KEY (ID_ARTICOLO) REFERENCES CATALOGO_ARTICOLI(ID_ARTICOLO),
    FOREIGN KEY (ID_LOCAZIONE) REFERENCES LOCAZIONI_MAGAZZINO(ID_LOCAZIONE),
    FOREIGN KEY (ID_RILEVATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Indici per le performance
CREATE INDEX IDX_INVENTARIO_ARTICOLO ON INVENTARIO(ID_ARTICOLO);
CREATE INDEX IDX_INVENTARIO_LOCAZIONE ON INVENTARIO(ID_LOCAZIONE);
CREATE INDEX IDX_MOVIMENTI_ARTICOLO ON MOVIMENTI_INVENTARIO(ID_ARTICOLO);
CREATE INDEX IDX_MOVIMENTI_TIPO ON MOVIMENTI_INVENTARIO(TIPO_MOVIMENTO);
CREATE INDEX IDX_MOVIMENTI_DATA ON MOVIMENTI_INVENTARIO(DATA_MOVIMENTO);
CREATE INDEX IDX_RILEVAMENTI_INVENTARIO ON RILEVAMENTI_INVENTARIO(ID_INVENTARIO_FISICO);