-- File: ordini_schema.sql
-- Descrizione: Schema per la gestione degli ordini di acquisto

-- Tabella delle richieste d'acquisto
CREATE TABLE RICHIESTE_ACQUISTO (
    ID_RICHIESTA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMERO_RICHIESTA VARCHAR(20) NOT NULL,
    ID_DIPARTIMENTO INTEGER NOT NULL,
    ID_RICHIEDENTE INTEGER NOT NULL, -- ID dipendente richiedente
    DATA_RICHIESTA DATE NOT NULL,
    DATA_NECESSITA DATE,
    MOTIVAZIONE VARCHAR(200),
    STATO VARCHAR(15) NOT NULL, -- 'BOZZA', 'RICHIESTA', 'APPROVATA', 'RIFIUTATA', 'COMPLETATA'
    DATA_APPROVAZIONE TIMESTAMP,
    ID_APPROVATORE INTEGER, -- ID dipendente approvatore
    NOTE_APPROVAZIONE VARCHAR(200),
    PRIMARY KEY (ID_RICHIESTA),
    UNIQUE (NUMERO_RICHIESTA),
    FOREIGN KEY (ID_DIPARTIMENTO) REFERENCES DIPARTIMENTI(ID_DIPARTIMENTO),
    FOREIGN KEY (ID_RICHIEDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella dei dettagli delle richieste
CREATE TABLE DETTAGLI_RICHIESTA (
    ID_DETTAGLIO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_RICHIESTA INTEGER NOT NULL,
    ID_ARTICOLO INTEGER,
    DESCRIZIONE_ARTICOLO VARCHAR(200), -- Per articoli non a catalogo
    QUANTITA DECIMAL(10,2) NOT NULL,
    UNITA_MISURA VARCHAR(10) NOT NULL,
    PREZZO_STIMATO DECIMAL(10,2),
    STATO VARCHAR(15) NOT NULL, -- 'RICHIESTO', 'APPROVATO', 'RIFIUTATO', 'ORDINATO', 'RICEVUTO'
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_DETTAGLIO),
    FOREIGN KEY (ID_RICHIESTA) REFERENCES RICHIESTE_ACQUISTO(ID_RICHIESTA),
    FOREIGN KEY (ID_ARTICOLO) REFERENCES CATALOGO_ARTICOLI(ID_ARTICOLO)
);

-- Tabella degli ordini di acquisto
CREATE TABLE ORDINI_ACQUISTO (
    ID_ORDINE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMERO_ORDINE VARCHAR(20) NOT NULL,
    ID_FORNITORE INTEGER NOT NULL,
    DATA_ORDINE DATE NOT NULL,
    DATA_CONSEGNA_PREVISTA DATE,
    CONDIZIONI_PAGAMENTO VARCHAR(100),
    INDIRIZZO_CONSEGNA VARCHAR(200),
    STATO VARCHAR(15) NOT NULL, -- 'BOZZA', 'EMESSO', 'CONFERMATO', 'PARZIALE', 'COMPLETATO', 'ANNULLATO'
    IMPORTO_TOTALE DECIMAL(12,2) NOT NULL,
    IMPORTO_IVA DECIMAL(12,2) NOT NULL,
    IMPORTO_TOTALE_IVA DECIMAL(12,2) NOT NULL,
    ID_CREATORE INTEGER NOT NULL, -- ID dipendente che ha creato l'ordine
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    DATA_MODIFICA TIMESTAMP,
    NOTE VARCHAR(500),
    PRIMARY KEY (ID_ORDINE),
    UNIQUE (NUMERO_ORDINE),
    FOREIGN KEY (ID_FORNITORE) REFERENCES FORNITORI(ID_FORNITORE),
    FOREIGN KEY (ID_CREATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella dei dettagli degli ordini
CREATE TABLE DETTAGLI_ORDINE (
    ID_DETTAGLIO_ORDINE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_ORDINE INTEGER NOT NULL,
    ID_DETTAGLIO_RICHIESTA INTEGER,
    ID_ARTICOLO INTEGER,
    DESCRIZIONE_ARTICOLO VARCHAR(200),
    QUANTITA_ORDINATA DECIMAL(10,2) NOT NULL,
    UNITA_MISURA VARCHAR(10) NOT NULL,
    PREZZO_UNITARIO DECIMAL(10,2) NOT NULL,
    ALIQUOTA_IVA DECIMAL(4,2) NOT NULL,
    IMPORTO_NETTO DECIMAL(10,2) NOT NULL,
    IMPORTO_IVA DECIMAL(10,2) NOT NULL,
    IMPORTO_TOTALE DECIMAL(10,2) NOT NULL,
    STATO VARCHAR(15) NOT NULL, -- 'ORDINATO', 'PARZIALE', 'RICEVUTO', 'ANNULLATO'
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_DETTAGLIO_ORDINE),
    FOREIGN KEY (ID_ORDINE) REFERENCES ORDINI_ACQUISTO(ID_ORDINE),
    FOREIGN KEY (ID_DETTAGLIO_RICHIESTA) REFERENCES DETTAGLI_RICHIESTA(ID_DETTAGLIO),
    FOREIGN KEY (ID_ARTICOLO) REFERENCES CATALOGO_ARTICOLI(ID_ARTICOLO)
);

-- Tabella delle ricezioni merci
CREATE TABLE RICEZIONI_MERCI (
    ID_RICEZIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMERO_RICEZIONE VARCHAR(20) NOT NULL,
    ID_ORDINE INTEGER NOT NULL,
    DATA_RICEZIONE DATE NOT NULL,
    NUMERO_DDT VARCHAR(20),
    DATA_DDT DATE,
    STATO VARCHAR(15) NOT NULL, -- 'BOZZA', 'REGISTRATO', 'VERIFICATO'
    ID_RICEVENTE INTEGER NOT NULL, -- ID dipendente che ha ricevuto la merce
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    NOTE VARCHAR(500),
    PRIMARY KEY (ID_RICEZIONE),
    UNIQUE (NUMERO_RICEZIONE),
    FOREIGN KEY (ID_ORDINE) REFERENCES ORDINI_ACQUISTO(ID_ORDINE),
    FOREIGN KEY (ID_RICEVENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella dei dettagli delle ricezioni
CREATE TABLE DETTAGLI_RICEZIONE (
    ID_DETTAGLIO_RICEZIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_RICEZIONE INTEGER NOT NULL,
    ID_DETTAGLIO_ORDINE INTEGER NOT NULL,
    QUANTITA_RICEVUTA DECIMAL(10,2) NOT NULL,
    QUANTITA_CONFORME DECIMAL(10,2) NOT NULL,
    QUANTITA_NON_CONFORME DECIMAL(10,2) DEFAULT 0,
    STATO VARCHAR(15) NOT NULL, -- 'RICEVUTO', 'VERIFICATO', 'NON_CONFORME', 'RESO'
    DATA_SCADENZA DATE,
    LOTTO VARCHAR(50),
    SERIALE VARCHAR(50),
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_DETTAGLIO_RICEZIONE),
    FOREIGN KEY (ID_RICEZIONE) REFERENCES RICEZIONI_MERCI(ID_RICEZIONE),
    FOREIGN KEY (ID_DETTAGLIO_ORDINE) REFERENCES DETTAGLI_ORDINE(ID_DETTAGLIO_ORDINE)
);

-- Indici per le performance
CREATE INDEX IDX_RICHIESTE_DIPARTIMENTO ON RICHIESTE_ACQUISTO(ID_DIPARTIMENTO);
CREATE INDEX IDX_RICHIESTE_RICHIEDENTE ON RICHIESTE_ACQUISTO(ID_RICHIEDENTE);
CREATE INDEX IDX_RICHIESTE_STATO ON RICHIESTE_ACQUISTO(STATO);
CREATE INDEX IDX_DETTAGLI_RICHIESTA ON DETTAGLI_RICHIESTA(ID_RICHIESTA);
CREATE INDEX IDX_ORDINI_FORNITORE ON ORDINI_ACQUISTO(ID_FORNITORE);
CREATE INDEX IDX_ORDINI_STATO ON ORDINI_ACQUISTO(STATO);
CREATE INDEX IDX_DETTAGLI_ORDINE ON DETTAGLI_ORDINE(ID_ORDINE);
CREATE INDEX IDX_RICEZIONI_ORDINE ON RICEZIONI_MERCI(ID_ORDINE);