-- File: report_acquisti.sql
-- Descrizione: Query per report sugli acquisti

-- Query per report ordini per fornitore
SELECT 
    F.RAGIONE_SOCIALE,
    COUNT(O.ID_ORDINE) AS NUMERO_ORDINI,
    SUM(O.IMPORTO_TOTALE) AS TOTALE_ORDINATO,
    MIN(O.DATA_ORDINE) AS DATA_PRIMO_ORDINE,
    MAX(O.DATA_ORDINE) AS DATA_ULTIMO_ORDINE
FROM ORDINI_ACQUISTO O
JOIN FORNITORI F ON O.ID_FORNITORE = F.ID_FORNITORE
WHERE O.DATA_ORDINE BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
GROUP BY F.RAGIONE_SOCIALE
ORDER BY TOTALE_ORDINATO DESC;

-- Query per report articoli più ordinati
SELECT 
    CA.CODICE_ARTICOLO,
    CA.NOME_ARTICOLO,
    SUM(DO.QUANTITA_ORDINATA) AS QUANTITA_TOTALE,
    SUM(DO.IMPORTO_NETTO) AS VALORE_TOTALE,
    COUNT(DISTINCT O.ID_ORDINE) AS NUMERO_ORDINI
FROM DETTAGLI_ORDINE DO
JOIN CATALOGO_ARTICOLI CA ON DO.ID_ARTICOLO = CA.ID_ARTICOLO
JOIN ORDINI_ACQUISTO O ON DO.ID_ORDINE = O.ID_ORDINE
WHERE O.DATA_ORDINE BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
GROUP BY CA.CODICE_ARTICOLO, CA.NOME_ARTICOLO
ORDER BY QUANTITA_TOTALE DESC;

-- Query per report acquisti per categoria
SELECT 
    CAT.NOME_CATEGORIA,
    COUNT(DISTINCT O.ID_ORDINE) AS NUMERO_ORDINI,
    SUM(DO.IMPORTO_NETTO) AS VALORE_TOTALE,
    AVG(DO.PREZZO_UNITARIO) AS PREZZO_MEDIO
FROM DETTAGLI_ORDINE DO
JOIN CATALOGO_ARTICOLI CA ON DO.ID_ARTICOLO = CA.ID_ARTICOLO
JOIN CATEGORIE_ARTICOLI CAT ON CA.ID_CATEGORIA = CAT.ID_CATEGORIA
JOIN ORDINI_ACQUISTO O ON DO.ID_ORDINE = O.ID_ORDINE
WHERE O.DATA_ORDINE BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
GROUP BY CAT.NOME_CATEGORIA
ORDER BY VALORE_TOTALE DESC;

-- Query per report acquisti per dipartimento
SELECT 
    D.NOME_DIPARTIMENTO,
    COUNT(DISTINCT RA.ID_RICHIESTA) AS NUMERO_RICHIESTE,
    COUNT(DISTINCT O.ID_ORDINE) AS NUMERO_ORDINI,
    SUM(O.IMPORTO_TOTALE) AS TOTALE_ORDINATO
FROM RICHIESTE_ACQUISTO RA
JOIN DIPARTIMENTI D ON RA.ID_DIPARTIMENTO = D.ID_DIPARTIMENTO
JOIN DETTAGLI_RICHIESTA DR ON RA.ID_RICHIESTA = DR.ID_RICHIESTA
JOIN DETTAGLI_ORDINE DO ON DR.ID_DETTAGLIO = DO.ID_DETTAGLIO_RICHIESTA
JOIN ORDINI_ACQUISTO O ON DO.ID_ORDINE = O.ID_ORDINE
WHERE O.DATA_ORDINE BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
GROUP BY D.NOME_DIPARTIMENTO
ORDER BY TOTALE_ORDINATO DESC;

-- Query per report tempi di consegna
SELECT 
    F.RAGIONE_SOCIALE,
    AVG(DAYS(RM.DATA_RICEZIONE) - DAYS(O.DATA_ORDINE)) AS GIORNI_MEDI_CONSEGNA,
    MIN(DAYS(RM.DATA_RICEZIONE) - DAYS(O.DATA_ORDINE)) AS GIORNI_MIN_CONSEGNA,
    MAX(DAYS(RM.DATA_RICEZIONE) - DAYS(O.DATA_ORDINE)) AS GIORNI_MAX_CONSEGNA,
    COUNT(DISTINCT O.ID_ORDINE) AS NUMERO_ORDINI
FROM ORDINI_ACQUISTO O
JOIN FORNITORI F ON O.ID_FORNITORE = F.ID_FORNITORE
JOIN RICEZIONI_MERCI RM ON O.ID_ORDINE = RM.ID_ORDINE
WHERE O.DATA_ORDINE BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
AND RM.DATA_RICEZIONE IS NOT NULL
GROUP BY F.RAGIONE_SOCIALE
ORDER BY GIORNI_MEDI_CONSEGNA;

-- Query per report storico prezzi
SELECT 
    CA.CODICE_ARTICOLO,
    CA.NOME_ARTICOLO,
    F.RAGIONE_SOCIALE,
    O.DATA_ORDINE,
    DO.PREZZO_UNITARIO
FROM DETTAGLI_ORDINE DO
JOIN CATALOGO_ARTICOLI CA ON DO.ID_ARTICOLO = CA.ID_ARTICOLO
JOIN ORDINI_ACQUISTO O ON DO.ID_ORDINE = O.ID_ORDINE
JOIN FORNITORI F ON O.ID_FORNITORE = F.ID_FORNITORE
WHERE DO.ID_ARTICOLO = :HV-ID-ARTICOLO
ORDER BY O.DATA_ORDINE DESC;