# Configurazione per la migrazione COBOL to Java
migration:
  source_encoding: "UTF-8"
  target_java_version: "11"
  
# Mappatura tipi COBOL -> Java
type_mappings:
  # Numerici
  "PIC 9": "int"
  #"PIC 9(n)": "int"  # n <= 9
  "PIC 9(n)": "long"  # n > 9
  "PIC S9": "int"
  "PIC 9V9": "BigDecimal"
  "PIC S9V9": "BigDecimal"
  
  # Alfanumerici
  "PIC X": "String"
  "PIC A": "String"
  
# Configurazione output Java
java:
  package_base: "com.bank.legacy"
  use_lombok: true
  generate_builders: true
  
# Spring Boot configuration
spring:
  version: "2.7.0"
  dependencies:
    - "spring-boot-starter-web"
    - "spring-boot-starter-data-jpa"
    - "postgresql"
    - "lombok"
    - "spring-boot-starter-validation"
  
# Database configuration
database:
  type: "postgresql"
  generate_entities: true
  use_jpa: true
  
# Docker configuration
docker:
  base_image: "openjdk:11-jre-slim"
  expose_port: 8080
  
# Logging
logging:
  level: "INFO"
  file: "migration.log"