-- File: budget_schema.sql
-- Descrizione: Schema per la gestione dei budget dipartimentali

-- Tabella dei periodi di budget
CREATE TABLE PERIODI_BUDGET (
    ID_PERIODO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ANNO INTEGER NOT NULL,
    NOME_PERIODO VARCHAR(50) NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE NOT NULL,
    STATO VARCHAR(15) NOT NULL, -- 'PIANIFICAZIONE', 'ATTIVO', 'CHIUSO'
    DATA_CHIUSURA DATE,
    PRIMARY KEY (ID_PERIODO),
    UNIQUE (ANNO, NOME_PERIODO)
);

-- Tabella delle categorie di budget
CREATE TABLE CATEGORIE_BUDGET (
    ID_CATEGORIA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME_CATEGORIA VARCHAR(50) NOT NULL,
    DESCRIZIONE VARCHAR(200),
    ATTIVA CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_CATEGORIA),
    UNIQUE (NOME_CATEGORIA)
);

-- Tabella dei budget dipartimentali
CREATE TABLE BUDGET_DIPARTIMENTO (
    ID_BUDGET INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPARTIMENTO INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    ID_CATEGORIA INTEGER NOT NULL,
    IMPORTO_PIANIFICATO DECIMAL(12,2) NOT NULL,
    IMPORTO_APPROVATO DECIMAL(12,2),
    IMPORTO_UTILIZZATO DECIMAL(12,2) DEFAULT 0,
    STATO VARCHAR(15) NOT NULL, -- 'BOZZA', 'PROPOSTO', 'APPROVATO', 'CHIUSO'
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    DATA_APPROVAZIONE TIMESTAMP,
    ID_APPROVATORE INTEGER,
    NOTE VARCHAR(500),
    PRIMARY KEY (ID_BUDGET),
    UNIQUE (ID_DIPARTIMENTO, ID_PERIODO, ID_CATEGORIA),
    FOREIGN KEY (ID_DIPARTIMENTO) REFERENCES DIPARTIMENTI(ID_DIPARTIMENTO),
    FOREIGN KEY (ID_PERIODO) REFERENCES PERIODI_BUDGET(ID_PERIODO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIE_BUDGET(ID_CATEGORIA)
);

-- Tabella delle revisioni di budget
CREATE TABLE REVISIONI_BUDGET (
    ID_REVISIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_BUDGET INTEGER NOT NULL,
    DATA_REVISIONE TIMESTAMP NOT NULL,
    IMPORTO_PRECEDENTE DECIMAL(12,2) NOT NULL,
    IMPORTO_NUOVO DECIMAL(12,2) NOT NULL,
    MOTIVO_REVISIONE VARCHAR(200) NOT NULL,
    ID_UTENTE_REVISIONE INTEGER NOT NULL,
    PRIMARY KEY (ID_REVISIONE),
    FOREIGN KEY (ID_BUDGET) REFERENCES BUDGET_DIPARTIMENTO(ID_BUDGET)
);

-- Indici per le performance
CREATE INDEX IDX_BUDGET_DIPARTIMENTO ON BUDGET_DIPARTIMENTO(ID_DIPARTIMENTO);
CREATE INDEX IDX_BUDGET_PERIODO ON BUDGET_DIPARTIMENTO(ID_PERIODO);
CREATE INDEX IDX_BUDGET_CATEGORIA ON BUDGET_DIPARTIMENTO(ID_CATEGORIA);
CREATE INDEX IDX_BUDGET_STATO ON BUDGET_DIPARTIMENTO(STATO);
CREATE INDEX IDX_REVISIONI_BUDGET ON REVISIONI_BUDGET(ID_BUDGET);