-- File: spese_schema.sql
-- Descrizione: Schema per la gestione delle spese

-- Tabella delle categorie di spesa
CREATE TABLE CATEGORIE_SPESA (
    ID_CATEGORIA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOME_CATEGORIA VARCHAR(50) NOT NULL,
    CATEGORIA_PADRE INTEGER,
    DESCRIZIONE VARCHAR(200),
    ATTIVA CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_CATEGORIA),
    UNIQUE (NOME_CATEGORIA),
    FOREIGN KEY (CATEGORIA_PADRE) REFERENCES CATEGORIE_SPESA(ID_CATEGORIA)
);

-- Tabella dei centri di costo
CREATE TABLE CENTRI_COSTO (
    ID_CENTRO_COSTO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODICE_CENTRO VARCHAR(20) NOT NULL,
    NOME_CENTRO VARCHAR(50) NOT NULL,
    ID_DIPARTIMENTO INTEGER NOT NULL,
    CENTRO_PADRE INTEGER,
    DESCRIZIONE VARCHAR(200),
    ATTIVO CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    DATA_CREAZIONE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_CENTRO_COSTO),
    UNIQUE (CODICE_CENTRO),
    FOREIGN KEY (ID_DIPARTIMENTO) REFERENCES DIPARTIMENTI(ID_DIPARTIMENTO),
    FOREIGN KEY (CENTRO_PADRE) REFERENCES CENTRI_COSTO(ID_CENTRO_COSTO)
);

-- Tabella delle spese
CREATE TABLE SPESE (
    ID_SPESA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_CENTRO_COSTO INTEGER NOT NULL,
    ID_CATEGORIA INTEGER NOT NULL,
    ID_BUDGET INTEGER, -- Budget associato (opzionale)
    DATA_SPESA DATE NOT NULL,
    DESCRIZIONE VARCHAR(200) NOT NULL,
    IMPORTO DECIMAL(12,2) NOT NULL,
    NUMERO_DOCUMENTO VARCHAR(30),
    DATA_DOCUMENTO DATE,
    ID_FORNITORE INTEGER, -- Fornitore associato (opzionale)
    ID_ORDINE INTEGER, -- Ordine associato (opzionale)
    STATO VARCHAR(15) NOT NULL, -- 'REGISTRATA', 'APPROVATA', 'PAGATA', 'CONTABILIZZATA'
    DATA_REGISTRAZIONE TIMESTAMP NOT NULL,
    ID_CREATORE INTEGER NOT NULL,
    DATA_APPROVAZIONE TIMESTAMP,
    ID_APPROVATORE INTEGER,
    NOTE VARCHAR(500),
    PRIMARY KEY (ID_SPESA),
    FOREIGN KEY (ID_CENTRO_COSTO) REFERENCES CENTRI_COSTO(ID_CENTRO_COSTO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIE_SPESA(ID_CATEGORIA),
    FOREIGN KEY (ID_BUDGET) REFERENCES BUDGET_DIPARTIMENTO(ID_BUDGET),
    FOREIGN KEY (ID_FORNITORE) REFERENCES FORNITORI(ID_FORNITORE),
    FOREIGN KEY (ID_ORDINE) REFERENCES ORDINI_ACQUISTO(ID_ORDINE),
    FOREIGN KEY (ID_CREATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE),
    FOREIGN KEY (ID_APPROVATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella delle allocazioni di spesa (per spese ripartite su più centri/budget)
CREATE TABLE ALLOCAZIONI_SPESA (
    ID_ALLOCAZIONE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_SPESA INTEGER NOT NULL,
    ID_CENTRO_COSTO INTEGER NOT NULL,
    ID_BUDGET INTEGER,
    PERCENTUALE DECIMAL(5,2) NOT NULL, -- Percentuale di allocazione
    IMPORTO DECIMAL(12,2) NOT NULL, -- Importo allocato
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_ALLOCAZIONE),
    FOREIGN KEY (ID_SPESA) REFERENCES SPESE(ID_SPESA),
    FOREIGN KEY (ID_CENTRO_COSTO) REFERENCES CENTRI_COSTO(ID_CENTRO_COSTO),
    FOREIGN KEY (ID_BUDGET) REFERENCES BUDGET_DIPARTIMENTO(ID_BUDGET)
);

-- Tabella dei pagamenti
CREATE TABLE PAGAMENTI (
    ID_PAGAMENTO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_SPESA INTEGER NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    IMPORTO_PAGATO DECIMAL(12,2) NOT NULL,
    METODO_PAGAMENTO VARCHAR(30) NOT NULL, -- 'BONIFICO', 'CARTA', 'CONTANTI', ecc.
    RIFERIMENTO_PAGAMENTO VARCHAR(50),
    ID_OPERATORE INTEGER NOT NULL,
    DATA_REGISTRAZIONE TIMESTAMP NOT NULL,
    NOTE VARCHAR(200),
    PRIMARY KEY (ID_PAGAMENTO),
    FOREIGN KEY (ID_SPESA) REFERENCES SPESE(ID_SPESA),
    FOREIGN KEY (ID_OPERATORE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Indici per le performance
CREATE INDEX IDX_SPESE_CENTRO_COSTO ON SPESE(ID_CENTRO_COSTO);
CREATE INDEX IDX_SPESE_CATEGORIA ON SPESE(ID_CATEGORIA);
CREATE INDEX IDX_SPESE_BUDGET ON SPESE(ID_BUDGET);
CREATE INDEX IDX_SPESE_DATA ON SPESE(DATA_SPESA);
CREATE INDEX IDX_SPESE_STATO ON SPESE(STATO);
CREATE INDEX IDX_ALLOCAZIONI_SPESA ON ALLOCAZIONI_SPESA(ID_SPESA);
CREATE INDEX IDX_ALLOCAZIONI_CENTRO_COSTO ON ALLOCAZIONI_SPESA(ID_CENTRO_COSTO);
CREATE INDEX IDX_ALLOCAZIONI_BUDGET ON ALLOCAZIONI_SPESA(ID_BUDGET);
CREATE INDEX IDX_PAGAMENTI_SPESA ON PAGAMENTI(ID_SPESA);