-- File: dipartimenti_base.sql
-- Descrizione: Query base per la gestione dei dipartimenti

-- Query per ottenere tutti i dipartimenti ordinati per nome
SELECT ID_DIPARTIMENTO, NOME_DIPARTIMENTO
FROM DIPARTIMENTI
ORDER BY NOME_DIPARTIMENTO;

-- Query per ottenere un dipartimento specifico
SELECT ID_DIPARTIMENTO, NOME_DIPARTIMENTO
FROM DIPARTIMENTI
WHERE ID_DIPARTIMENTO = :HV-ID-DIPARTIMENTO;

-- Query per inserire un nuovo dipartimento
INSERT INTO DIPARTIMENTI (NOME_DIPARTIMENTO)
VALUES (:HV-NOME-DIPARTIMENTO);

-- Query per aggiornare un dipartimento esistente
UPDATE DIPARTIMENTI
SET NOME_DIPARTIMENTO = :HV-NOME-DIPARTIMENTO
WHERE ID_DIPARTIMENTO = :HV-ID-DIPARTIMENTO;

-- Query per eliminare un dipartimento (solo se non ha posizioni associate)
DELETE FROM DIPARTIMENTI
WHERE ID_DIPARTIMENTO = :HV-ID-DIPARTIMENTO
AND NOT EXISTS (
    SELECT 1 FROM POSIZIONI
    WHERE ID_DIPARTIMENTO = :HV-ID-DIPARTIMENTO
);

-- Query per contare i dipendenti per dipartimento
SELECT D.NOME_DIPARTIMENTO, COUNT(DIP.ID_DIPENDENTE) AS NUMERO_DIPENDENTI
FROM DIPARTIMENTI D
LEFT JOIN POSIZIONI P ON D.ID_DIPARTIMENTO = P.ID_DIPARTIMENTO
LEFT JOIN DIPENDENTI DIP ON P.ID_POSIZIONE = DIP.ID_POSIZIONE
GROUP BY D.NOME_DIPARTIMENTO
ORDER BY D.NOME_DIPARTIMENTO;