-- File: dipendenti_base.sql
-- Descrizione: Query base per la gestione dei dipendenti

-- Query per ottenere tutti i dipendenti ordinati per nome
SELECT ID_DIPENDENTE, NOME, ID_POSIZIONE, DATA_ASSUNZIONE
FROM DIPENDENTI
ORDER BY NOME;

-- Query per ottenere un dipendente specifico
SELECT ID_DIPENDENTE, NOME, ID_POSIZIONE, DATA_ASSUNZIONE
FROM DIPENDENTI
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE;

-- Query per ottenere dipendenti per posizione
SELECT D.ID_DIPENDENTE, D.NOME, D.DATA_ASSUNZIONE, P.NOME_POSIZIONE
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
WHERE P.ID_POSIZIONE = :HV-ID-POSIZIONE
ORDER BY D.NOME;

-- Query per inserire un nuovo dipendente
INSERT INTO DIPENDENTI (ID_DIPENDENTE, NOME, ID_POSIZIONE, DATA_ASSUNZIONE)
VALUES (:HV-ID-DIPENDENTE, :HV-NOME, :HV-ID-POSIZIONE, :HV-DATA-ASSUNZIONE);

-- Query per aggiornare un dipendente esistente
UPDATE DIPENDENTI
SET NOME = :HV-NOME,
    ID_POSIZIONE = :HV-ID-POSIZIONE,
    DATA_ASSUNZIONE = :HV-DATA-ASSUNZIONE
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE;

-- Query per eliminare un dipendente
DELETE FROM DIPENDENTI
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE;