-- File: posizioni_base.sql
-- Descrizione: Query base per la gestione delle posizioni lavorative

-- Query per ottenere tutte le posizioni ordinate per nome
SELECT ID_POSIZIONE, NOME_POSIZIONE, STIPENDIO_BASE, ID_DIPARTIMENTO
FROM POSIZIONI
ORDER BY NOME_POSIZIONE;

-- Query per ottenere posizioni per dipartimento
SELECT P.ID_POSIZIONE, P.NOME_POSIZIONE, P.STIPENDIO_BASE, D.NOME_DIPARTIMENTO
FROM POSIZIONI P
JOIN DIPARTIMENTI D ON P.ID_DIPARTIMENTO = D.ID_DIPARTIMENTO
WHERE P.ID_DIPARTIMENTO = :HV-ID-DIPARTIMENTO
ORDER BY P.NOME_POSIZIONE;

-- Query per ottenere una posizione specifica
SELECT ID_POSIZIONE, NOME_POSIZIONE, STIPENDIO_BASE, ID_DIPARTIMENTO
FROM POSIZIONI
WHERE ID_POSIZIONE = :HV-ID-POSIZIONE;

-- Query per inserire una nuova posizione
INSERT INTO POSIZIONI (NOME_POSIZIONE, STIPENDIO_BASE, ID_DIPARTIMENTO)
VALUES (:HV-NOME-POSIZIONE, :HV-STIPENDIO-BASE, :HV-ID-DIPARTIMENTO);

-- Query per aggiornare una posizione esistente
UPDATE POSIZIONI
SET NOME_POSIZIONE = :HV-NOME-POSIZIONE,
    STIPENDIO_BASE = :HV-STIPENDIO-BASE,
    ID_DIPARTIMENTO = :HV-ID-DIPARTIMENTO
WHERE ID_POSIZIONE = :HV-ID-POSIZIONE;

-- Query per eliminare una posizione (solo se non ha dipendenti associati)
DELETE FROM POSIZIONI
WHERE ID_POSIZIONE = :HV-ID-POSIZIONE
AND NOT EXISTS (
    SELECT 1 FROM DIPENDENTI
    WHERE ID_POSIZIONE = :HV-ID-POSIZIONE
);