-- File: query_anagrafica.sql
-- Descrizione: Query complesse per l'anagrafica

-- Query per elenco dipendenti con dettagli di posizione e dipartimento
SELECT 
    D.ID_DIPENDENTE, 
    D.NOME, 
    D.DATA_ASSUNZIONE,
    P.NOME_POSIZIONE,
    P.STIPENDIO_BASE,
    DP.NOME_DIPARTIMENTO
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
ORDER BY DP.NOME_DIPARTIMENTO, P.NOME_POSIZIONE, D.NOME;

-- Query per dipendenti assunti nell'ultimo anno
SELECT 
    D.ID_DIPENDENTE, 
    D.NOME, 
    D.DATA_ASSUNZIONE,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
WHERE D.DATA_ASSUNZIONE >= CURRENT DATE - 1 YEAR
ORDER BY D.DATA_ASSUNZIONE DESC;

-- Query per anzianità di servizio
SELECT 
    D.ID_DIPENDENTE, 
    D.NOME, 
    D.DATA_ASSUNZIONE,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    DAYS(CURRENT DATE) - DAYS(D.DATA_ASSUNZIONE) AS GIORNI_ANZIANITA,
    YEAR(CURRENT DATE) - YEAR(D.DATA_ASSUNZIONE) - 
    CASE 
        WHEN MONTH(CURRENT DATE) < MONTH(D.DATA_ASSUNZIONE) OR 
            (MONTH(CURRENT DATE) = MONTH(D.DATA_ASSUNZIONE) AND 
             DAY(CURRENT DATE) < DAY(D.DATA_ASSUNZIONE)) 
        THEN 1 
        ELSE 0 
    END AS ANNI_ANZIANITA
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
ORDER BY GIORNI_ANZIANITA DESC;

-- Query per distribuzione dipendenti per dipartimento
SELECT 
    DP.NOME_DIPARTIMENTO,
    COUNT(D.ID_DIPENDENTE) AS NUMERO_DIPENDENTI,
    MIN(D.DATA_ASSUNZIONE) AS DATA_ASSUNZIONE_PIU_VECCHIA,
    MAX(D.DATA_ASSUNZIONE) AS DATA_ASSUNZIONE_PIU_RECENTE
FROM DIPARTIMENTI DP
JOIN POSIZIONI P ON DP.ID_DIPARTIMENTO = P.ID_DIPARTIMENTO
JOIN DIPENDENTI D ON P.ID_POSIZIONE = D.ID_POSIZIONE
GROUP BY DP.NOME_DIPARTIMENTO
ORDER BY NUMERO_DIPENDENTI DESC;

-- Query per distribuzione stipendi
SELECT 
    DP.NOME_DIPARTIMENTO,
    AVG(P.STIPENDIO_BASE) AS STIPENDIO_MEDIO,
    MIN(P.STIPENDIO_BASE) AS STIPENDIO_MINIMO,
    MAX(P.STIPENDIO_BASE) AS STIPENDIO_MASSIMO,
    COUNT(D.ID_DIPENDENTE) AS NUMERO_DIPENDENTI
FROM DIPARTIMENTI DP
JOIN POSIZIONI P ON DP.ID_DIPARTIMENTO = P.ID_DIPARTIMENTO
JOIN DIPENDENTI D ON P.ID_POSIZIONE = D.ID_POSIZIONE
GROUP BY DP.NOME_DIPARTIMENTO
ORDER BY STIPENDIO_MEDIO DESC;

-- Query per distribuzione posizioni
SELECT 
    P.NOME_POSIZIONE,
    COUNT(D.ID_DIPENDENTE) AS NUMERO_DIPENDENTI,
    P.STIPENDIO_BASE
FROM POSIZIONI P
JOIN DIPENDENTI D ON P.ID_POSIZIONE = D.ID_POSIZIONE
GROUP BY P.NOME_POSIZIONE, P.STIPENDIO_BASE
ORDER BY NUMERO_DIPENDENTI DESC;