# docker-compose.yml per COBOL to Java Migration Tool
version: '3.8'

services:
  # Migration Tool
  migrator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cobol-migration-tool
    volumes:
      # Monta la directory con i file COBOL/SQL
      - ./test-files:/app/input:ro
      # Monta la directory di output
      - ./output:/app/output
      # Monta la directory per i logs
      - ./logs:/app/logs
      # Monta la configurazione (opzionale)
      - ./config:/app/config:ro
    environment:
      # Configurazioni di ambiente
      PYTHONPATH: /app/src
      LOG_LEVEL: INFO
    # Comando di default (può essere sovrascritto)
    command: >
      --input /app/input/bank_system.cbl
      --schema /app/input/bank_schema.sql
      --output /app/output
      --config /app/config/migration-config.yaml
      --debug
    
  # Servizio per sviluppo interattivo
  migrator-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cobol-migration-dev
    volumes:
      - ./test-files:/app/input:ro
      - ./output:/app/output
      - ./logs:/app/logs
      - ./config:/app/config:ro
      # Monta anche il codice sorgente per sviluppo
      - ./src:/app/src
    environment:
      PYTHONPATH: /app/src
      LOG_LEVEL: DEBUG
    # Mantiene il container in vita per debugging
    entrypoint: ["tail", "-f", "/dev/null"]
    profiles: ["dev"]

  # Nginx per servire i file generati (opzionale)
  file-server:
    image: nginx:alpine
    container_name: migration-file-server
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - migrator
    profiles: ["serve"]