-- File: ferie_gestione.sql
-- Descrizione: Query per la gestione delle ferie

-- Query per calcolo ferie residue
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    F.ANNO,
    F.GIORNI_SPETTANTI,
    F.GIORNI_GODUTI,
    F.GIORNI_RESIDUI,
    F.SCADENZA
FROM DIPENDENTI D
JOIN FERIE F ON D.ID_DIPENDENTE = F.ID_DIPENDENTE
WHERE D.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND F.ANNO = :HV-ANNO;

-- Query per elenco richieste ferie
SELECT 
    RF.ID_RICHIESTA,
    D.NOME,
    RF.DATA_INIZIO,
    RF.DATA_FINE,
    RF.TOTALE_GIORNI,
    RF.STATO,
    RF.MOTIVAZIONE,
    RF.DATA_RICHIESTA,
    RF.DATA_APPROVAZIONE,
    DA.NOME AS NOME_APPROVATORE
FROM RICHIESTE_FERIE RF
JOIN DIPENDENTI D ON RF.ID_DIPENDENTE = D.ID_DIPENDENTE
LEFT JOIN DIPENDENTI DA ON RF.ID_APPROVATORE = DA.ID_DIPENDENTE
WHERE RF.ID_DIPENDENTE = :HV-ID-DIPENDENTE
ORDER BY RF.DATA_RICHIESTA DESC;

-- Query per richieste ferie in attesa di approvazione
SELECT 
    RF.ID_RICHIESTA,
    D.NOME,
    RF.DATA_INIZIO,
    RF.DATA_FINE,
    RF.TOTALE_GIORNI,
    RF.MOTIVAZIONE,
    RF.DATA_RICHIESTA,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO
FROM RICHIESTE_FERIE RF
JOIN DIPENDENTI D ON RF.ID_DIPENDENTE = D.ID_DIPENDENTE
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
WHERE RF.STATO = 'RICHIESTA'
ORDER BY RF.DATA_RICHIESTA;

-- Query per inserire una nuova richiesta ferie
INSERT INTO RICHIESTE_FERIE (
    ID_DIPENDENTE, DATA_INIZIO, DATA_FINE, TOTALE_GIORNI,
    STATO, MOTIVAZIONE, DATA_RICHIESTA
) VALUES (
    :HV-ID-DIPENDENTE, :HV-DATA-INIZIO, :HV-DATA-FINE, :HV-TOTALE-GIORNI,
    'RICHIESTA', :HV-MOTIVAZIONE, CURRENT TIMESTAMP
);

-- Query per approvare una richiesta ferie
UPDATE RICHIESTE_FERIE
SET STATO = 'APPROVATA',
    DATA_APPROVAZIONE = CURRENT TIMESTAMP,
    ID_APPROVATORE = :HV-ID-APPROVATORE,
    NOTE_APPROVAZIONE = :HV-NOTE-APPROVAZIONE
WHERE ID_RICHIESTA = :HV-ID-RICHIESTA;

-- Query per rifiutare una richiesta ferie
UPDATE RICHIESTE_FERIE
SET STATO = 'RIFIUTATA',
    DATA_APPROVAZIONE = CURRENT TIMESTAMP,
    ID_APPROVATORE = :HV-ID-APPROVATORE,
    NOTE_APPROVAZIONE = :HV-NOTE-APPROVAZIONE
WHERE ID_RICHIESTA = :HV-ID-RICHIESTA;

-- Query per aggiornare il saldo ferie dopo approvazione
UPDATE FERIE
SET GIORNI_GODUTI = GIORNI_GODUTI + :HV-TOTALE-GIORNI,
    GIORNI_RESIDUI = GIORNI_SPETTANTI - (GIORNI_GODUTI + :HV-TOTALE-GIORNI)
WHERE ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND ANNO = :HV-ANNO;

-- Query per calendario ferie per dipartimento
SELECT 
    D.NOME,
    RF.DATA_INIZIO,
    RF.DATA_FINE,
    RF.TOTALE_GIORNI,
    DP.NOME_DIPARTIMENTO
FROM RICHIESTE_FERIE RF
JOIN DIPENDENTI D ON RF.ID_DIPENDENTE = D.ID_DIPENDENTE
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
WHERE RF.STATO = 'APPROVATA'
AND DP.ID_DIPARTIMENTO = :HV-ID-DIPARTIMENTO
AND (
    (RF.DATA_INIZIO BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE) OR
    (RF.DATA_FINE BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE) OR
    (RF.DATA_INIZIO <= :HV-DATA-INIZIO AND RF.DATA_FINE >= :HV-DATA-FINE)
)
ORDER BY RF.DATA_INIZIO;