-- File: presenze_reports.sql
-- Descrizione: Query per report sulle presenze

-- Query per report mensile presenze per dipendente
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    COUNT(PR.ID_PRESENZA) AS GIORNI_LAVORATI,
    SUM(CASE WHEN PR.TIPO_GIORNATA = 'LAVORO' THEN 1 ELSE 0 END) AS GIORNI_PRESENZA,
    SUM(CASE WHEN PR.TIPO_GIORNATA = 'FERIE' THEN 1 ELSE 0 END) AS GIORNI_FERIE,
    SUM(CASE WHEN PR.TIPO_GIORNATA = 'MALATTIA' THEN 1 ELSE 0 END) AS GIORNI_MALATTIA,
    SUM(CASE WHEN PR.TIPO_GIORNATA = 'PERMESSO' THEN 1 ELSE 0 END) AS GIORNI_PERMESSO,
    SUM(PR.MINUTI_LAVORATI) / 60 AS ORE_LAVORATE
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
LEFT JOIN PRESENZE PR ON D.ID_DIPENDENTE = PR.ID_DIPENDENTE
WHERE EXTRACT(YEAR FROM PR.DATA) = :HV-ANNO
AND EXTRACT(MONTH FROM PR.DATA) = :HV-MESE
GROUP BY D.ID_DIPENDENTE, D.NOME, P.NOME_POSIZIONE, DP.NOME_DIPARTIMENTO
ORDER BY DP.NOME_DIPARTIMENTO, D.NOME;

-- Query per report assenze per dipartimento
SELECT 
    DP.NOME_DIPARTIMENTO,
    COUNT(DISTINCT D.ID_DIPENDENTE) AS NUMERO_DIPENDENTI,
    SUM(CASE WHEN PR.TIPO_GIORNATA = 'FERIE' THEN 1 ELSE 0 END) AS TOTALE_GIORNI_FERIE,
    SUM(CASE WHEN PR.TIPO_GIORNATA = 'MALATTIA' THEN 1 ELSE 0 END) AS TOTALE_GIORNI_MALATTIA,
    SUM(CASE WHEN PR.TIPO_GIORNATA = 'PERMESSO' THEN 1 ELSE 0 END) AS TOTALE_GIORNI_PERMESSO
FROM DIPARTIMENTI DP
JOIN POSIZIONI P ON DP.ID_DIPARTIMENTO = P.ID_DIPARTIMENTO
JOIN DIPENDENTI D ON P.ID_POSIZIONE = D.ID_POSIZIONE
LEFT JOIN PRESENZE PR ON D.ID_DIPENDENTE = PR.ID_DIPENDENTE
WHERE EXTRACT(YEAR FROM PR.DATA) = :HV-ANNO
AND EXTRACT(MONTH FROM PR.DATA) = :HV-MESE
GROUP BY DP.NOME_DIPARTIMENTO
ORDER BY DP.NOME_DIPARTIMENTO;

-- Query per report ore straordinarie
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    COUNT(PR.ID_PRESENZA) AS GIORNI_CON_STRAORDINARIO,
    SUM(CASE WHEN PR.MINUTI_LAVORATI > 480 THEN PR.MINUTI_LAVORATI - 480 ELSE 0 END) / 60 AS ORE_STRAORDINARIO
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
JOIN PRESENZE PR ON D.ID_DIPENDENTE = PR.ID_DIPENDENTE
WHERE EXTRACT(YEAR FROM PR.DATA) = :HV-ANNO
AND EXTRACT(MONTH FROM PR.DATA) = :HV-MESE
AND PR.TIPO_GIORNATA = 'LAVORO'
AND PR.MINUTI_LAVORATI > 480
GROUP BY D.ID_DIPENDENTE, D.NOME, P.NOME_POSIZIONE, DP.NOME_DIPARTIMENTO
ORDER BY ORE_STRAORDINARIO DESC;

-- Query per report ferie residue
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    P.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    F.ANNO,
    F.GIORNI_SPETTANTI,
    F.GIORNI_GODUTI,
    F.GIORNI_RESIDUI,
    F.SCADENZA
FROM DIPENDENTI D
JOIN POSIZIONI P ON D.ID_POSIZIONE = P.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON P.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
JOIN FERIE F ON D.ID_DIPENDENTE = F.ID_DIPENDENTE
WHERE F.ANNO = :HV-ANNO
ORDER BY DP.NOME_DIPARTIMENTO, D.NOME;