-- File: presenze_schema.sql
-- Descrizione: Schema per la gestione delle presenze

-- Tabella dei giorni lavorativi
CREATE TABLE GIORNI_LAVORATIVI (
    ID_GIORNO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DATA DATE NOT NULL,
    GIORNO_SETTIMANA INTEGER NOT NULL, -- 1=Lunedì, 7=Domenica
    FESTIVITA VARCHAR(50),
    LAVORATIVO CHAR(1) NOT NULL DEFAULT 'S', -- 'S'=Sì, 'N'=No
    PRIMARY KEY (ID_GIORNO),
    UNIQUE (DATA)
);

-- Tabella delle presenze
CREATE TABLE PRESENZE (
    ID_PRESENZA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    DATA DATE NOT NULL,
    ORA_ENTRATA TIME,
    ORA_USCITA TIME,
    MINUTI_LAVORATI INTEGER,
    TIPO_GIORNATA VARCHAR(10) NOT NULL, -- 'LAVORO', 'FERIE', 'MALATTIA', 'PERMESSO'
    NOTE VARCHAR(200),
    DATA_INSERIMENTO TIMESTAMP NOT NULL,
    DATA_MODIFICA TIMESTAMP,
    PRIMARY KEY (ID_PRESENZA),
    UNIQUE (ID_DIPENDENTE, DATA),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella delle ferie
CREATE TABLE FERIE (
    ID_FERIE INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    ANNO INTEGER NOT NULL,
    GIORNI_SPETTANTI INTEGER NOT NULL,
    GIORNI_GODUTI INTEGER NOT NULL DEFAULT 0,
    GIORNI_RESIDUI INTEGER NOT NULL,
    SCADENZA DATE,
    PRIMARY KEY (ID_FERIE),
    UNIQUE (ID_DIPENDENTE, ANNO),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Tabella delle richieste ferie
CREATE TABLE RICHIESTE_FERIE (
    ID_RICHIESTA INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_DIPENDENTE INTEGER NOT NULL,
    DATA_INIZIO DATE NOT NULL,
    DATA_FINE DATE NOT NULL,
    TOTALE_GIORNI INTEGER NOT NULL,
    STATO VARCHAR(10) NOT NULL, -- 'RICHIESTA', 'APPROVATA', 'RIFIUTATA'
    MOTIVAZIONE VARCHAR(200),
    DATA_RICHIESTA TIMESTAMP NOT NULL,
    DATA_APPROVAZIONE TIMESTAMP,
    ID_APPROVATORE INTEGER,
    NOTE_APPROVAZIONE VARCHAR(200),
    PRIMARY KEY (ID_RICHIESTA),
    FOREIGN KEY (ID_DIPENDENTE) REFERENCES DIPENDENTI(ID_DIPENDENTE)
);

-- Indici per le performance
CREATE INDEX IDX_PRESENZE_DIPENDENTE ON PRESENZE(ID_DIPENDENTE);
CREATE INDEX IDX_PRESENZE_DATA ON PRESENZE(DATA);
CREATE INDEX IDX_RICHIESTE_DIPENDENTE ON RICHIESTE_FERIE(ID_DIPENDENTE);
CREATE INDEX IDX_RICHIESTE_STATO ON RICHIESTE_FERIE(STATO);