-- File: query_presenze.sql
-- Descrizione: Query per la gestione delle presenze

-- Query per inserire una nuova presenza
INSERT INTO PRESENZE (
    ID_DIPENDENTE, DATA, ORA_ENTRATA, ORA_USCITA,
    MINUTI_LAVORATI, TIPO_GIORNATA, NOTE, DATA_INSERIMENTO
) VALUES (
    :HV-ID-DIPENDENTE, :HV-DATA, :HV-ORA-ENTRATA, :HV-ORA-USCITA,
    :HV-MINUTI-LAVORATI, :HV-TIPO-GIORNATA, :HV-NOTE, CURRENT TIMESTAMP
);

-- Query per aggiornare una presenza esistente
UPDATE PRESENZE
SET ORA_ENTRATA = :HV-ORA-ENTRATA,
    ORA_USCITA = :HV-ORA-USCITA,
    MINUTI_LAVORATI = :HV-MINUTI-LAVORATI,
    TIPO_GIORNATA = :HV-TIPO-GIORNATA,
    NOTE = :HV-NOTE,
    DATA_MODIFICA = CURRENT TIMESTAMP
WHERE ID_PRESENZA = :HV-ID-PRESENZA;

-- Query per ottenere le presenze di un dipendente in un periodo
SELECT 
    P.ID_PRESENZA,
    P.DATA,
    P.ORA_ENTRATA,
    P.ORA_USCITA,
    P.MINUTI_LAVORATI,
    P.TIPO_GIORNATA,
    P.NOTE,
    CASE 
        WHEN GL.LAVORATIVO = 'S' THEN 'Lavorativo' 
        ELSE 'Non lavorativo' 
    END AS TIPO_GIORNO,
    GL.FESTIVITA
FROM PRESENZE P
LEFT JOIN GIORNI_LAVORATIVI GL ON P.DATA = GL.DATA
WHERE P.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND P.DATA BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
ORDER BY P.DATA;

-- Query per calcolare le ore lavorate in un mese
SELECT 
    SUM(P.MINUTI_LAVORATI) / 60 AS ORE_LAVORATE
FROM PRESENZE P
WHERE P.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND YEAR(P.DATA) = :HV-ANNO
AND MONTH(P.DATA) = :HV-MESE
AND P.TIPO_GIORNATA = 'LAVORO';

-- Query per calcolare le ore straordinarie in un mese
SELECT 
    SUM(CASE WHEN P.MINUTI_LAVORATI > 480 THEN P.MINUTI_LAVORATI - 480 ELSE 0 END) / 60 AS ORE_STRAORDINARIO
FROM PRESENZE P
JOIN GIORNI_LAVORATIVI GL ON P.DATA = GL.DATA
WHERE P.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND YEAR(P.DATA) = :HV-ANNO
AND MONTH(P.DATA) = :HV-MESE
AND P.TIPO_GIORNATA = 'LAVORO'
AND GL.LAVORATIVO = 'S';

-- Query per calcolare i giorni di assenza per tipo
SELECT 
    P.TIPO_GIORNATA,
    COUNT(*) AS GIORNI_ASSENZA
FROM PRESENZE P
JOIN GIORNI_LAVORATIVI GL ON P.DATA = GL.DATA
WHERE P.ID_DIPENDENTE = :HV-ID-DIPENDENTE
AND YEAR(P.DATA) = :HV-ANNO
AND MONTH(P.DATA) = :HV-MESE
AND P.TIPO_GIORNATA <> 'LAVORO'
AND GL.LAVORATIVO = 'S'
GROUP BY P.TIPO_GIORNATA;

-- Query per presenze giornaliere per dipartimento
SELECT 
    P.DATA,
    DP.NOME_DIPARTIMENTO,
    COUNT(DISTINCT P.ID_DIPENDENTE) AS DIPENDENTI_PRESENTI,
    SUM(CASE WHEN P.TIPO_GIORNATA = 'LAVORO' THEN 1 ELSE 0 END) AS PRESENZE,
    SUM(CASE WHEN P.TIPO_GIORNATA = 'FERIE' THEN 1 ELSE 0 END) AS FERIE,
    SUM(CASE WHEN P.TIPO_GIORNATA = 'MALATTIA' THEN 1 ELSE 0 END) AS MALATTIE,
    SUM(CASE WHEN P.TIPO_GIORNATA = 'PERMESSO' THEN 1 ELSE 0 END) AS PERMESSI
FROM PRESENZE P
JOIN DIPENDENTI D ON P.ID_DIPENDENTE = D.ID_DIPENDENTE
JOIN POSIZIONI POS ON D.ID_POSIZIONE = POS.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON POS.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
WHERE P.DATA BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
GROUP BY P.DATA, DP.NOME_DIPARTIMENTO
ORDER BY P.DATA, DP.NOME_DIPARTIMENTO;

-- Query per dipendenti assenti oggi
SELECT 
    D.ID_DIPENDENTE,
    D.NOME,
    POS.NOME_POSIZIONE,
    DP.NOME_DIPARTIMENTO,
    P.TIPO_GIORNATA,
    P.NOTE
FROM DIPENDENTI D
JOIN POSIZIONI POS ON D.ID_POSIZIONE = POS.ID_POSIZIONE
JOIN DIPARTIMENTI DP ON POS.ID_DIPARTIMENTO = DP.ID_DIPARTIMENTO
LEFT JOIN PRESENZE P ON D.ID_DIPENDENTE = P.ID_DIPENDENTE AND P.DATA = CURRENT DATE
JOIN GIORNI_LAVORATIVI GL ON GL.DATA = CURRENT DATE
WHERE GL.LAVORATIVO = 'S'
AND (P.TIPO_GIORNATA <> 'LAVORO' OR P.ID_PRESENZA IS NULL)
ORDER BY DP.NOME_DIPARTIMENTO, D.NOME;

-- Query per tassi di assenza per dipartimento
SELECT 
    DP.NOME_DIPARTIMENTO,
    COUNT(DISTINCT D.ID_DIPENDENTE) AS TOTALE_DIPENDENTI,
    COUNT(DISTINCT P.ID_DIPENDENTE) AS DIPENDENTI_CON_ASSENZE,
    SUM(CASE WHEN P.TIPO_GIORNATA = 'MALATTIA' THEN 1 ELSE 0 END) AS GIORNI_MALATTIA,
    SUM(CASE WHEN P.TIPO_GIORNATA = 'FERIE' THEN 1 ELSE 0 END) AS GIORNI_FERIE,
    SUM(CASE WHEN P.TIPO_GIORNATA = 'PERMESSO' THEN 1 ELSE 0 END) AS GIORNI_PERMESSO,
    DECIMAL(SUM(CASE WHEN P.TIPO_GIORNATA <> 'LAVORO' THEN 1 ELSE 0 END) * 100.0 / 
            (SELECT COUNT(*) FROM GIORNI_LAVORATIVI WHERE LAVORATIVO = 'S' AND DATA BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE) / 
            COUNT(DISTINCT D.ID_DIPENDENTE), 5, 2) AS PERCENTUALE_ASSENZA
FROM DIPARTIMENTI DP
JOIN POSIZIONI POS ON DP.ID_DIPARTIMENTO = POS.ID_DIPARTIMENTO
JOIN DIPENDENTI D ON POS.ID_POSIZIONE = D.ID_POSIZIONE
LEFT JOIN PRESENZE P ON D.ID_DIPENDENTE = P.ID_DIPENDENTE 
                    AND P.DATA BETWEEN :HV-DATA-INIZIO AND :HV-DATA-FINE
                    AND P.TIPO_GIORNATA <> 'LAVORO'
GROUP BY DP.NOME_DIPARTIMENTO
ORDER BY PERCENTUALE_ASSENZA DESC;